### ISSUE TITLE
New install, license key error

### ISSUE THREAD

**Issue by micro2112** [robpodcloud/robpod-studio#1]
Trying to install and test out the trial period, but it did not pull a trial license. That setting page is blank.

**Comment by robpodcloud** [comment]
Hi,
looks like Robpod Studio is not able to retrieve the PC identifier.
What Operating System / Virtual Machine are you using?

**Comment by micro2112** [comment]
Win10 system. Any way to manually load that info?

**Comment by robpodcloud** [comment]
Very strange, Win10 is preferred operating system for Robpod Studio.
Could you share **idea.log** files located in directory C:\Users\\{USER}\AppData\Local\JetBrains\PyCharmCE2023.2\log ?

**Comment by micro2112** [comment]
Sure thing. 
I chose to install only for my user instead of all, if that helps at all. 

[idea.log](https://github.com/robpodcloud/robpod-studio/files/13565794/idea.log)

**Comment by robpodcloud** [comment]
Thanks for the logs, i think is the WSL - Windows Subsystem for Linux that is interferring with standard machine commands.
I will prepare a fix version for this issue and release it tomorrow.

**Comment by micro2112** [comment]
Awesome. Thank you

**Comment by robpodcloud** [comment]
Fix release is ready: https://github.com/robpodcloud/robpod-studio/releases/tag/1.1.4
Could you install it and try again?

**Comment by micro2112** [comment]
Success! Thank you. 
 ![image](https://github.com/robpodcloud/robpod-studio/assets/9109887/40cc1222-015c-47d4-a184-e52916494551)
