### ISSUE TITLE
Wrong generated Python Script from UR script for RoboDK simulation

### ISSUE THREAD

**Issue by davidmospina** [robpodcloud/robpod-studio#2]
After the development of a simple example script tested successfully on the real robot, a simulation run on RoboDK was not possible as the python script for RoboDK was generated with problems of indentation and functions naming:

After the development of a simple example script tested successfully on the real robot, a simulation run on RoboDK was not possible as the python script for RoboDK was generated with problems of indentation and functions naming.

**UR script:**
```urscript
thread postrack():
    while True:
        poseJ = get_actual_joint_positions()
        textmsg("current position is: ", poseJ)
        sleep(2)
        
        poseTool = get_actual_tcp_pose()
        textmsg("current tool position is: ", poseTool)
        sleep(2)
    end
end

run postrack()

global iteration = 0

while iteration < 3:
    movej([-0.03, -1.78, 1.85, 4.59, -1.63, 0.00])
    movej([0.39, -1.78, 1.84, 4.63, -1.64, 0.42])
    movej([0.39, -1.78, 1.84, 4.63, -1.64, 0.42])
    movej([1.11, -1.54, 1.62, 4.67, -1.64, 1.15])

    iteration = iteration + 1
end
```

**auto generated Python script with errors:**
```python
from UR import *; def postrack():
	while True:
		poseJ = get_actual_joint_positions()
		textmsg("current position is: ", poseJ)
		sleep(2)
		
		poseTool = get_actual_tcp_pose()
		textmsg("current tool position is: ", poseTool)
		sleep(2)
	


start_thread(target=postrack)

iteration = globals()['iteration'] = 0

while iteration < 3:

    movej([-0.03, -1.78, 1.85, 4.59, -1.63, 0.00])
    movej([0.39, -1.78, 1.84, 4.63, -1.64, 0.42])
    movej([0.39, -1.78, 1.84, 4.63, -1.64, 0.42])
    movej([1.11, -1.54, 1.62, 4.67, -1.64, 1.15])

    iteration = globals()['iteration'] = iteration + 1

**Comment by robpodcloud** [comment]
Hi David, thanks for the report.

You can solve by simply adding a comment or blank line at begging of the UR script:

![immagine](https://github.com/robpodcloud/robpod-studio/assets/113412912/0aaa52da-1785-4c3d-acf8-2dc54bfe4880)

Issue is caused because Robpod Studio keeps same lines match between UR script and generated python programs.

**Comment by davidmospina** [comment]
Thank you for the fast answer! all fixed!
